### ISSUE TITLE
Settings screen?

### ISSUE THREAD

**Issue by vinkaga** [OLayemii/uberr-ui#30]
Excellent work! Would love to have a settings screen. 
Thanks.

**Comment by olayemii** [comment]
Hello @vinkaga there's a mini preferences page when you click on the caret on the user profile

![Screenshot_20200501_143703_com example uberr](https://user-images.githubusercontent.com/11563148/80809281-3ef9f280-8bb9-11ea-8a44-dc2d31786e99.jpg)

If you need more than this.. Let me know..

**Comment by vinkaga** [comment]
Thanks.
